name: generate animation

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite rodar manualmente a qualquer momento
  workflow_dispatch:
  
  # Roda a cada push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera o jogo da cobrinha com as suas cores personalizadas
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#f8efd4&color_dots=#402b23,#5d3427,#7c3d2d,#9d4435,#bf4a3f
            dist/github-contribution-grid-snake-dark.svg?color_snake=#f8efd4&color_dots=#402b23,#5d3427,#7c3d2d,#9d4435,#bf4a3f

      # Envia os arquivos gerados para a branch 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
